### ISSUE TITLE
How good is esp32 supported?

### ISSUE THREAD

**Issue by stm01** [LowPowerLab/RFM69#173] opened 2021-10-04 21:17 UTC
Hi there!
I tried to compile the rxtxblinky for the esp32 and got stuck with several errors.

Digging deeper i found some lines in the source, which seem to me, there is some kind of support for the esp32.

Can someone tell me, how good the esp32 is supported and which examples work without too mich hassle to get started with this supernice library?
Gesetz Stephan

**Comment by LowPowerLab** [comment] 2021-10-04 23:08
Hi Stephan, It's not officially supported by me (the creator) but others posted PRs to add in various pieces to support. But the problem is the esp32 platforms are so many. However you should be able to invoke the constructor with the CS and IRQ pins for your particular ESP32 to override the defaults `RFM69(slaveSelectPin, interruptPin, isRFM69HW)`.
There is also [this forum](https://lowpowerlab.com/forum/esp32-esp8266/) where others have discussed this library with respect to esp32/support.
Since this is not a bug report I will now close this issue.

**Closed by LowPowerLab** 2021-10-04 23:08 UTC
