### ISSUE TITLE
RFM69W with a 1MHz Arduino sends duplicate messages

### ISSUE THREAD

**Issue by thenounoursk** [LowPowerLab/RFM69#128] opened 2020-01-05 16:49 UTC
Hi,
I've recently discovered MySensors and started to use it to build nodes, using your library. One node is an Arduino Pro Mini (3.3v) which I downgraded to 1MHz. You can read more at: https://forum.mysensors.org/topic/10855/arduino-promini-3-3v-on-1mhz-rfm69w-missing-acks/7

Basically, when I keep everything else the same, a node downgraded to 1MHz vs a node running at normal 8MHz clock speed, my 1MHz node sends duplicate messages (I receive duplicates on my Gateway). The 8Mhz node, same code and everything, doesn't have duplicates... It's not systematic though, and at times, I only get one message on my gateway, but most of the times, I get duplicates (up to 5 which is the maximum this library will retry to send I believe). 

Would you any idea what needs to be done for this library to perform better when used in combination with a 1MHz arduino? 

Best regards,

Florent

**Comment by LowPowerLab** [comment] 2020-01-06 15:13
You need to investigate at the SPI bus level perhaps, with a logic analyzer. I believe your SPI bus might be too slow.

This library was designed to work on 8 and 16Mhz Moteino boards which are more/less compatible with UNO/Genuino but running at 3.3V.

Since this is not really a documented issue I will close this now.

**Closed by LowPowerLab** 2020-01-06 15:13 UTC
